Models/Personaggi.cs
namespace Pathfinder.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Personaggi")]
    public partial class Personaggi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personaggi()
        {
            Users_Personaggi = new HashSet<Users_Personaggi>();
        }

        [Key]
        public int IdPg { get; set; }
        public string Img { get; set; }

        [Required]
        [StringLength(50)]
        public string Nome { get; set; }
        [Required]
        public int IdRazza { get; set; }
        [Required]
        public int IdClasse { get; set; }
        [Required]
        public int Forza { get; set; }
        [Required]
        public int Destrezza { get; set; }
        [Required]
        public int Costituzione { get; set; }
        [Required]
        public int Intelligenza { get; set; }
        [Required]
        public int Saggezza { get; set; }
        [Required]
        public int Carisma { get; set; }

        public int PuntiVita { get; set; }

        public int Livello { get; set; }

        public virtual Classi Classi { get; set; }

        public virtual Razze Razze { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users_Personaggi> Users_Personaggi { get; set; }
        public virtual ICollection<Abilita_Personaggio> Abilita_Personaggio { get; set; }
    }
}

Models/PersonaggiViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Pathfinder.Models
{
    public class PersonaggiViewModel
    {
        [Required(ErrorMessage = "Devi scegliere un Nome")]
        public string Nome { get; set; }
        [Required(ErrorMessage = "Devi scegliere una Razza")]
        public int IdRazza { get; set; }
        [Required(ErrorMessage = "Devi scegliere una Classe")]
        public int IdClasse { get; set; }
        public int Forza { get; set; }

        public int Destrezza { get; set; }

        public int Costituzione { get; set; }

        public int Intelligenza { get; set; }

        public int Saggezza { get; set; }

        public int Carisma { get; set; }

        public int PuntiVita { get; set; }
        public int Livello { get; set; }       

        public List<Razze> RazzeList { get; set; }
        public List<Classi> ClassiList { get; set; }
        public List<string> AbilitaClasse { get; set; }
        public List<AbilitaViewModel> AbilitaList { get; set; }
        public PersonaggiViewModel()
        {
            Livello = 1;
        }

        public class AbilitaViewModel
        {
            public int IdAbilita { get; set; }
            public string Nome { get; set; }
            public int Valore { get; set; }
        }
    }    
}

Controllers/AvventuraController.cs
using Pathfinder.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pathfinder.Controllers
{
    [Authorize]
    public class AvventuraController : Controller
    {
        ModelDBContext db = new ModelDBContext();
        // GET: Avventura
        public ActionResult Index()
        {
            var username = User.Identity.Name;
            var personaggi = db.Users.FirstOrDefault(u => u.Username == username)?.Users_Personaggi.Select(up => up.Personaggi).ToList();
            return View(personaggi);
        }

        public ActionResult Seleziona(int IdPg)
        {
            TempData["IdPg"] = IdPg;
            return RedirectToAction("PrimaParte");
        }

        public ActionResult PrimaParte()
        {
            if (TempData["IdPg"] == null)
            {
                return View();
            }
            var idPg = (int)TempData["IdPg"];
            var personaggio = db.Personaggi.FirstOrDefault(p => p.IdPg == idPg);
            if (personaggio == null)
            {
                return HttpNotFound();
            }
            return View(personaggio);
        }

        public ActionResult SecondaParte(int idPg)
        {
            var personaggio = db.Personaggi.FirstOrDefault(p => p.IdPg == idPg);
            if (personaggio == null)
            {
                return HttpNotFound();
            }
            return View(personaggio);
        }

        public ActionResult TerzaParte(int idPg)
        {
            var personaggio = db.Personaggi.FirstOrDefault(p => p.IdPg == idPg);
            if (personaggio == null)
            {
                return HttpNotFound();
            }
            return View(personaggio);
        }
    }
}

Controllers/GuidaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pathfinder.Controllers
{
    [AllowAnonymous]
    public class GuidaController : Controller
    {
        // GET: Guida
        public ActionResult Home()
        {
            return View();
        }
        public ActionResult Indice() 
        {
            return View();
        }
        public ActionResult Caratteristiche()
        {
            return View();
        }
        public ActionResult Razze()
        {
            return View();
        }
        public ActionResult Classi()
        {
            return View();
        }
        public ActionResult Abilita()
        {
            return View();
        }

        public ActionResult Talenti() 
        {
            return View();
        }
        public FileResult DownloadPdf()
        {
            string filePath = Server.MapPath("~/Content/Pathfinder_SchedaPersonaggio.pdf");
            string contentType = "application/pdf";
            string fileName = "Pathfinder_SchedaPersonaggio.pdf";

            return File(filePath, contentType, fileName);
        }
    }
}

Controllers/PersonaggiController.cs
using Pathfinder.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace Pathfinder.Controllers
{
    [Authorize]
    public class PersonaggiController : Controller
    {
        ModelDBContext db = new ModelDBContext();
        // GET: Personaggi
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Intro() 
        {
            return View();
        }
        public ActionResult Create() 
        {
            var viewModel = new PersonaggiViewModel
            {
                RazzeList = db.Razze.ToList(),
                ClassiList = db.Classi.ToList()
            };
            return View(viewModel);            
        }        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PersonaggiViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var classe = db.Classi.FirstOrDefault(c => c.IdClasse == viewModel.IdClasse);
                var modificatoreCostituzione = CalcolaModificatore(viewModel.Costituzione);
                var puntiVita = 10 + modificatoreCostituzione;
                var personaggio = new Personaggi
                {
                    Nome = viewModel.Nome,
                    IdRazza = viewModel.IdRazza,
                    IdClasse = viewModel.IdClasse,
                    Forza = viewModel.Forza,
                    Destrezza = viewModel.Destrezza,
                    Costituzione = viewModel.Costituzione,
                    Intelligenza = viewModel.Intelligenza,
                    Saggezza = viewModel.Saggezza,
                    Carisma = viewModel.Carisma,
                    PuntiVita = puntiVita,
                    Livello = 1,
                    Abilita_Personaggio = new List<Abilita_Personaggio>()
                };

                db.Personaggi.Add(personaggio);
                db.SaveChanges();
                var abilitaClasse = db.Abilita_Classe
                            .Where(ac => ac.IdClasse == viewModel.IdClasse && ac.Abilita != null)
                            .Select(ac => ac.Abilita)
                            .ToList();

                foreach (var abilita in abilitaClasse)
                {
                    var valoreAbilita = CalcolaValoreAbilita(abilita, viewModel.Forza, viewModel.Destrezza, viewModel.Costituzione, viewModel.Intelligenza, viewModel.Saggezza, viewModel.Carisma);
                    var abilitaPersonaggio = new Abilita_Personaggio
                    {
                        IdPg = personaggio.IdPg,
                        IdAbilita = abilita.IdAbilita,
                        Valore = valoreAbilita
                    };
                    db.Abilita_Personaggio.Add(abilitaPersonaggio);
                }
                db.SaveChanges();

                var utenteCorrente = db.Users.FirstOrDefault(u => u.Username == User.Identity.Name);
                if (utenteCorrente != null)
                {
                    utenteCorrente.Users_Personaggi.Add(new Users_Personaggi
                    {
                        Username = utenteCorrente.Username,
                        IdPg = personaggio.IdPg
                    });
                    db.SaveChanges();
                }

                return RedirectToAction("Index", "Personaggi");
            }

            viewModel.Livello = 1;
            viewModel.RazzeList = db.Razze.ToList();
            viewModel.ClassiList = db.Classi.ToList();
            return View("Create", viewModel);
        }
        private int CalcolaModificatore(int valoreCaratteristica)
        {
            return (valoreCaratteristica - 10) / 2;
        }
        public JsonResult GetClassInfo(int idClasse)
        {
            var classe = db.Classi.FirstOrDefault(c => c.IdClasse == idClasse);
            if (classe == null)
            {
                return Json(null);
            }

            var classInfo = new
            {
                bonusAttaccoBase = classe.BonusAttaccoBase,
                tsTempra = classe.TSTempra,
                tsRiflessi = classe.TSRiflessi,
                tsVolonta = classe.TSVolonta
            };
            return Json(classInfo, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetAbilitaClasse(int idClasse, int forza, int destrezza, int costituzione, int intelligenza, int saggezza, int carisma)
        {
            var abilita = db.Abilita_Classe
                .Where(ac => ac.IdClasse == idClasse && ac.Abilita != null)
                .Select(ac => new
                {
                    Abilita = ac.Abilita,
                    CaratteristicaAssociata = ac.Abilita.CaratteristicaAssociata,
                    Tipo = ac.Abilita.Tipo
                })
                .ToList()
                .Select(ac => new
                {
                    IdAbilita = ac.Abilita.IdAbilita,
                    Nome = ac.Abilita.Nome,
                    CaratteristicaAssociata = ac.CaratteristicaAssociata,
                    Tipo = ac.Tipo,
                    Valore = CalcolaValoreAbilita(ac.Abilita, forza, destrezza, costituzione, intelligenza, saggezza, carisma)
                })
                .ToList();

            return Json(abilita, JsonRequestBehavior.AllowGet);
        }

        private int CalcolaValoreAbilita(Abilita abilita, int forza, int destrezza, int costituzione, int intelligenza, int saggezza, int carisma)
        {
            int valoreCaratteristica = 0;

            switch (abilita.CaratteristicaAssociata)
            {
                case "Forza":
                    valoreCaratteristica = forza;
                    break;
                case "Destrezza":
                    valoreCaratteristica = destrezza;
                    break;
                case "Costituzione":
                    valoreCaratteristica = costituzione;
                    break;
                case "Intelligenza":
                    valoreCaratteristica = intelligenza;
                    break;
                case "Saggezza":
                    valoreCaratteristica = saggezza;
                    break;
                case "Carisma":
                    valoreCaratteristica = carisma;
                    break;
                default:
                    break;
            }
            int modificatore = (valoreCaratteristica - 10) / 2;
            if (modificatore == -1 && valoreCaratteristica >= 10)
            {
                return 0;
            }
            return modificatore + 1;
        }
        public ActionResult PersonaggiUtente()
        {
            var username = User.Identity.Name;
            var personaggi = db.Users.FirstOrDefault(u => u.Username == username)?.Users_Personaggi.Select(up => up.Personaggi).ToList();
            return View(personaggi);
        }
        public ActionResult EliminaPersonaggio(int idPg)
        {
            var personaggioDaEliminare = db.Personaggi.Find(idPg);
            if (personaggioDaEliminare != null)
            {
                db.Abilita_Personaggio.RemoveRange(personaggioDaEliminare.Abilita_Personaggio);
                db.Users_Personaggi.RemoveRange(personaggioDaEliminare.Users_Personaggi);
                db.Personaggi.Remove(personaggioDaEliminare);
                db.SaveChanges();
                return RedirectToAction("PersonaggiUtente");
            }
            else
            {
                return HttpNotFound();
            }
        }
        public FileResult DownloadPdf()
        {
            string filePath = Server.MapPath("~/Content/Pathfinder_SchedaPersonaggio.pdf");
            string contentType = "application/pdf";
            string fileName = "Pathfinder_SchedaPersonaggio.pdf";

            return File(filePath, contentType, fileName);
        }
    }
}

Views/Personaggi/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<main class="mainColor">
    <div id="imgMimic">
        <h1 class="mb-4">Benvenuto, avventuriero!</h1>
        <h3 class="text-center mb-5">Qui, puoi decidere cosa fare:</h3>
    </div>    
    <div id="divIndexPersonaggi">
        <p class="welcome linkPersonaggi">@Html.ActionLink("Crea un nuovo personaggio", "Intro", "Personaggi", new { area = "" })</p>
        <p class="welcome linkPersonaggi">@Html.ActionLink("Visualizza i tuoi personaggi", "PersonaggiUtente", "Personaggi", new { area = "" })</p>
        <p class="welcome linkPersonaggi">@Html.ActionLink("Consulta la guida", "Indice", "Guida")</p>
        <p class="welcome linkPersonaggi">@Html.ActionLink("Prova un'avventura!", "Index", "Avventura")</p>
    </div>
    <p class="pdfText link-1">Puoi scaricare il pdf della Scheda Personaggio ufficiale di Pathfinder: <a href="@Url.Action("DownloadPdf", "Personaggi")">cliccando qui!</a></p>
</main>

Views/Personaggi/Intro.cshtml
@{
    ViewBag.Title = "Intro";
}
<main class="mainColor">
    <div id="intro" class="imgDrago">
        <h2 class="mb-3">Creare un personaggio</h2>
        <p class="sectionText">
            Il primo passo per giocare a un'avventura nel gioco <span class="parolaChiave">Pathfinder</span> è immaginare e creare un personaggio tutto tuo.
            <br />
            Il tuo personaggio è una combinazione di statistiche di gioco, agganci di interpretazione e della tua immaginazione.
            Scegli una @Html.ActionLink("razza", "Razze", "Guida", new { area = "" }, new { @class = "parolaChiave" }) (come <span class="parolaChiave" onclick="redirectToUmani()">umano</span> o <span class="parolaChiave" onclick="redirectToHalfing()">halfling</span>) e una @Html.ActionLink("classe", "Classi", "Guida", new { area = "" }, new { @class = "parolaChiave" }) (come <span class="parolaChiave">guerriero</span> o <span class="parolaChiave">mago</span>).
            Inventi anche la personalità, l'aspetto e la storia del tuo personaggio.
            <br />
            Una volta completato, il tuo personaggio funge da tuo rappresentante nel gioco, il tuo avatar nel mondo di Pathfinder.
            Prima di immergerti nel costruttore del personaggio, pensa al tipo di avventuriero che vuoi interpretare.
            Potresti essere un coraggioso combattente, un losco malandrino, un fervente <span class="parolaChiave">chierico</span> o un <span class="parolaChiave">mago</span> sfavillante.
            Oppure potresti essere più interessato a un personaggio non convenzionale, come un furfante muscoloso che preferisce il combattimento corpo a corpo, o un tiratore scelto che colpisce i nemici da lontano.
            Ti piace la narrativa fantasy con <span class="parolaChiave" onclick="redirectToNani()">nani</span> o <span class="parolaChiave" onclick="redirectToElfi()">elfi</span>? Prova a costruire un personaggio di una di quelle razze.
            Vuoi che il tuo personaggio sia l'avventuriero più resistente del gruppo? Considera una classe come <span class="parolaChiave">barbaro</span> o <span class="parolaChiave">paladino</span>.
            <br />
            Una volta che hai in mente un personaggio, segui i passaggi in questo costruttore in ordine, facendo scelte che riflettano il personaggio che desideri.
            La tua concezione del tuo personaggio potrebbe evolvere con ogni scelta che fai.
            Ciò che è importante è che tu arrivi al tavolo con un personaggio che ti entusiasma interpretare.
        </p>
        <p class="small">P.s. Il sito è in continuo aggiornamento, non tutti i contenuti sono disponibili da subito.</p>
    </div>
    <div id="containerBtnIntro">
        <div class="buttonsIntro">
            <button onclick="redirectToPage('/Personaggi/Create')">Succ.</button>
            <button onclick="redirectToPage('/Personaggi/Index')">Prev.</button>
        </div>
    </div>

</main>

Views/Personaggi/PersonaggiUtente.cshtml
@using Pathfinder.Models
@model List<Personaggi>

@{
    ViewBag.Title = "I tuoi Personaggi";
}
<main>
    <div id="divTopPgUtente">
        <h1 class="mainColor">I tuoi Personaggi</h1>
        <button id="btnIndietro">@Html.ActionLink("Torna indietro", "Index", "Personaggi", new { area = "" })</button>
    </div>

    @if (Model.Any())
    {
        <div class="table-wrapper">
            <table class="fl-table">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Razza</th>
                        <th>Classe</th>
                        <th>Forza</th>
                        <th>Destrezza</th>
                        <th>Costituzione</th>
                        <th>Intelligenza</th>
                        <th>Saggezza</th>
                        <th>Carisma</th>
                        <th>PuntiVita</th>
                        <th>Livello</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var personaggio in Model)
                    {
                        <tr>
                            <td>@personaggio.Nome</td>
                            <td>@personaggio.Razze.Tipologia</td>
                            <td>@personaggio.Classi.Nome</td>
                            <td>@personaggio.Forza</td>
                            <td>@personaggio.Destrezza</td>
                            <td>@personaggio.Costituzione</td>
                            <td>@personaggio.Intelligenza</td>
                            <td>@personaggio.Saggezza</td>
                            <td>@personaggio.Carisma</td>
                            <td>@personaggio.PuntiVita</td>
                            <td>@personaggio.Livello</td>
                            <td>
                                <button type="button" class="btn btn-danger btnElimina" data-toggle="modal" data-target="#eliminaModal-@personaggio.IdPg">
                                    Elimina
                                </button>
                                <div class="modal fade" id="eliminaModal-@personaggio.IdPg" tabindex="-1" role="dialog" aria-labelledby="eliminaModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="eliminaModalLabel">Conferma Eliminazione</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                Sei sicuro di voler eliminare questo personaggio?
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annulla</button>
                                                <a href="@Url.Action("EliminaPersonaggio", new { idPg = personaggio.IdPg })" class="btn btn-danger">Elimina</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }
    else
    {
        <p class="welcome noPg">Non hai nessun personaggio. @Html.ActionLink("Prova a farne uno!", "Create", "Personaggi", new { area = "" })</p>
    }
</main>